name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: damianhoward/.github/.github/workflows/ci.yml@main
    with:
      coverage-report-files: core/build/reports/jacoco/test/jacocoTestReport.xml,app/build/reports/jacoco/test/jacocoTestReport.xml
      test-report-paths: |
        core/build/reports/tests/test
        app/build/reports/tests/test
    secrets: inherit
